name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{POSTGRES_DB }}
          POSTGRES_USER: ${{ POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ POSTGRES_PASSWORD }}
        options: >-
          --health-cmd "pg_isready -U ${{ POSTGRES_USER }} -d ${{ POSTGRES_DB }}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and tag Docker image
        run: |
          docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache --tag cv-builder-api:latest .
          docker tag cv-builder-api:latest ${{ DOCKER_USERNAME }}/cv-builder-api:latest

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Test the application
        run: docker-compose exec cv-builder-api mvn test

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ DOCKER_USERNAME }}
          password: ${{ DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --tag ${{ DOCKER_USERNAME }}/cv-builder-api:latest --push .

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ DEPLOY_USER }}@${{ DEPLOY_HOST }} << 'EOF'
          docker pull ${{ DOCKER_USERNAME }}/cv-builder-api:latest
          docker stop cv-builder-api || true
          docker rm cv-builder-api || true
          docker run -d -p 8081:8081 --name cv-builder-api ${{ DOCKER_USERNAME }}/cv-builder-api:latest
          EOF